# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e0e10a0932cf2644027f49b823cfb9668424f40b36df0fd480994ab701b6a253203df84423512ac4282695dcfd56bfb887f8da163fb03b81bde33cac7d31de9

test:
  secret_key_base: 46910e7bf0eaecc3a2723829a2cd645b9e3416ad9427ca819642e9687275e660fc7e2d32b4d1320e18d8fb9effe5541902085cc809b0394e311cf0ab546ce57c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
